name: lts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cmake
  - dlib
  - portaudio
  - pip:
      - customtkinter
      - packaging
      - aiohttp
      - colorama
      - psutil
      - pyserial
      - python-dotenv
      - SpeechRecognition
      - keyboard
      - PyAudio
      - pillow
      - PyPDF2
      - numpy
      - pandas
      - pynvml
      - opencv-python
      - face_recognition
      - mediapipe
      - google-generativeai
      - chromadb
      - pydantic
      - langchain
      - langchain-google-genai
      - llama-cpp-python
      - flask
      - flask-cors
      - flask-socketio
      - werkzeug
      - requests
      - beautifulsoup4
      - googlesearch-python
      - wikipedia
      - instaloader
      - facebook-scraper
      - pytrends
      - selenium
      - webdriver-manager
      - ccxt
      - ta
      - mplfinance
      - matplotlib
      - edge-tts
      - pygame
      - python-docx
      - PyYAML
      - TTS
