name: lts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cmake
  - dlib
  - portaudio
  - numpy=1.24.3
  - pandas=1.5.3
  - pip:
      - customtkinter
      - packaging
      - aiohttp==3.9.3
      - colorama==0.4.6
      - psutil==5.9.8
      - pyserial==3.5
      - python-dotenv==1.0.1
      - SpeechRecognition==3.10.4
      - keyboard==0.13.5
      - PyAudio==0.2.14
      - Pillow==10.2.0
      - PyPDF2==3.0.1
      - pynvml==11.5.0
      - opencv-python==4.9.0.80
      - face_recognition==1.3.0
      - mediapipe==0.10.11
      - google-generativeai==0.4.1
      - chromadb==0.4.24
      - pydantic==2.6.4
      - langchain==0.1.12
      - langchain-google-genai==1.0.1
      - llama-cpp-python
      - flask==3.0.2
      - flask-cors==4.0.0
      - flask-socketio==5.3.6
      - werkzeug==3.0.1
      - requests==2.31.0
      - beautifulsoup4==4.12.3
      - googlesearch-python==1.2.3
      - wikipedia==1.4.0
      - instaloader==4.11
      - facebook-scraper
      - pytrends==4.9.2
      - selenium==4.18.1
      - webdriver-manager==4.0.1
      - ccxt==4.2.66
      - ta==0.11.0
      - mplfinance==0.12.10b0
      - matplotlib==3.8.3
      - edge-tts==6.1.10
      - pygame==2.5.2
      - python-docx==1.1.0
      - PyYAML==6.0.1
      - TTS==0.22.0
